### ISSUE TITLE
Calling A Teams User or Voice App  limits to IDs of type 8:orgid 

### ISSUE THREAD

**Issue by GauravES** [Azure-Samples/communication-services-web-calling-hero#253]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Update code or Provide instructions on how to use the Calling Sample to call a Call Queue or AutoAttendant or any Phone Resource Account in Teams.  These do not seem to have 8:org IDs.    The non React demos allow for calling 8:echo123 for testing as well which is ACS Echo bot.  The React sample blocks that

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> Latest version as of 2024-10-17

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by GauravES** [comment]
![image](https://github.com/user-attachments/assets/bc9de3da-18dd-4e13-9330-510b31758e98)

**Comment by mgamis-msft** [comment]
Hi @GauravES, sorry for slow response. 
You can call call queue of auto attendant by entering the user id of the associated resource account. You can find out the user id of resource account using Microsoft Graph Explorer as described in our [storybook page](https://azure.github.io/communication-ui-library/?path=/docs/concepts-ad-hoc-calling--docs#obtaining-the-id-of-a-teams-user-or-call-queue). In that documentation, we did forget to mention that resource accounts are prefixed by '28:orgid:' instead of '8:orgid:' so make sure to keep that in mind.
