### ISSUE TITLE
Black video view on both device and laptop

### ISSUE THREAD

**Issue by mastoj** [Azure-Samples/communication-services-web-calling-hero#44]
**Describe the bug**

One or both of the video vies are black when making the call. It works occasionally, but it should be reliable.

**To Reproduce**
1. Deploy app
2. Start call from laptop
3. Join from phone
4. One or both screens are black. If not from start it happens when switching camera.

**Expected behavior**

Expected both video views to work smooth.

**Screenshots**

Here is what I see on laptop: 

![az com](https://user-images.githubusercontent.com/501424/114147130-aadff180-9918-11eb-8668-e0855f48dd7f.png)

Here is what I see on iPhone:

![IMG_2312](https://user-images.githubusercontent.com/501424/114147248-ce0aa100-9918-11eb-95e1-55f593248608.PNG)

**Desktop (please complete the following information):**
- OS laptop: Pop OS (linux)
- Version: "20.10"
- Browser: Chrome

**Smartphone (please complete the following information):**
 - IOS software version: 14.4.2 
 - Safari

**Logs**
I see some 

> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

on client in browser logs.

**Comment by alkwa-msft** [comment]
Thanks for sharing this issue. Will be looking into this!

**Comment by alkwa-msft** [comment]
While I am following up with the calling team I wanted to share this page. It looks like we have specified compatibility specifically for Ubuntu (Linux)

https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#calling-client-library-browser-support

**Comment by akania** [comment]
@mastoj thank you for reporting, as @alkwa-msft mentioned , Pop OS is not on our support list, I'd still like to look at this issue
can you please 

Capture `call.id` - To instrument your code to capture `call.id` ( https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#access-your-call-id )

Capture full verbose log - Instrument your code to capture full log https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#enable-and-access-call-logs

1. repro scenario ( when you see black video frame )
2. hangup the call normally on both sides, don't close applications on either of side so our internal metrics will be sent out

Reply here with 'call.id' you've captured and send logs to `acsfeedback@microsoft.com` and mention this GH issue #


Follow up question - does this happen if you use same iPhone/Safari on one side but on the other e.g. MacOs/Safari or Windows/Edge or Chrome instead of Pop/Chrome ?

**Comment by mastoj** [comment]
I’ll get on it as soon as I have time. Pop is basically based on Ubuntu, so the underlying bits should be the same as Ubuntu.

**Comment by alkwa-msft** [comment]
Closing this issue. It sounds like we are in a slightly unsupported area. If there are additional issues please feel free to open a ticket here or https://github.com/Azure/Communication/issues
